table ImagemGrupoProduto
	lineageTag: bd6ee339-6409-4307-a3cf-8dcc5f53e7f8

	column 'Grupo Produto'
		dataType: string
		lineageTag: 81c29af3-31de-4ce8-9c7b-dd0eb62c92cb
		summarizeBy: none
		sourceColumn: Grupo Produto

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: d6f5780c-8a3a-476f-bce1-a9a935000462
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	partition ImagemGrupoProduto = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents( PastaCaminhoArquivo & "Produtos.xlsx"), null, true),
				    ImagemGrupoProduto_Sheet = Fonte{[Item="ImagemGrupoProduto",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(ImagemGrupoProduto_Sheet,{{"Column1", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"URL", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

